configuration: Debug
image: Visual Studio 2017

environment:
  MIK_TEX_INSTALL_DIR: 'C:\MikTex\'

version: '7.4.0.{build}'

assembly_info:
  patch: true
  file: SolutionInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version} - EAP"

clone_depth: 1

cache:
  packages -> **\packages.config 

install:
- set PATH=C:\Ruby25\bin;%PATH%
- git submodule update --init --recursive
- gem install xml-simple
- ps: >-
    (new-object net.webclient).DownloadFile('https://github.com/Open-Systems-Pharmacology/MiKTeX/releases/download/v2.9.3/MikTex.2.9.3.msi', 'C:\MikTex.msi')

    Start-Process msiexec.exe -ArgumentList /i, C:\MikTex.msi, /quiet, /qn, /norestart, INSTALLDIR=$env:MIK_TEX_INSTALL_DIR -Wait
- ps: >-
    (new-object net.webclient).DownloadFile('https://ci.appveyor.com/api/projects/Open-Systems-Pharmacology-ci/smartxls/artifacts/OSPSuite.SmartXLS.2.6.4.1.nupkg', 'C:\smartxls.zip')

before_build:
  - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
  - nuget sources add -name utility -source https://ci.appveyor.com/nuget/ospsuite-utility 
  - nuget sources add -name serializer -source https://ci.appveyor.com/nuget/ospsuite-serializer 
  - nuget sources add -name texreporting -source https://ci.appveyor.com/nuget/ospsuite-texreporting 
  - nuget sources add -name databinding -source https://ci.appveyor.com/nuget/ospsuite-databinding 
  - nuget sources add -name databinding-devexpress -source https://ci.appveyor.com/nuget/ospsuite-databinding-devexpress 
  - nuget sources add -name funcparser -source https://ci.appveyor.com/nuget/ospsuite-funcparser 
  - nuget sources add -name simmodel -source https://ci.appveyor.com/nuget/ospsuite-simmodel
  - nuget sources add -name cvodes -source https://ci.appveyor.com/nuget/ospsuite-simmodel-solver-cvodes-282
  - nuget sources add -name core -source https://ci.appveyor.com/nuget/ospsuite-core
  - nuget restore
  - rake "update_go_license[ApplicationStartup.cs, %GO_DIAGRAM_KEY%]"
  
after_build:
  - rake "create_setup[%APPVEYOR_BUILD_VERSION%, %CONFIGURATION%, C:/smartxls.zip, 2.6.4.1]"
  - 7z a setup.zip %APPVEYOR_BUILD_FOLDER%\setup\deploy\*.msi
  - rake "create_portable_setup[%APPVEYOR_BUILD_VERSION%, %CONFIGURATION%, mobi-portable-setup.zip]"

build:
  verbosity: minimal
  project: MoBi.sln

test:
  assemblies:
    - MoBi.Tests.dll
    - MoBi.UI.Tests.dll

on_finish: 
  - ps: Get-ChildItem setup.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\setup\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

skip_commits:
  files:
    - '*.md'

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=
