name: Build and Test V13

on:
  pull_request:
    branches:
    - v13

jobs:

  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Restore dependencies
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"
          dotnet restore

      - name: Build
        run: dotnet build MoBi.sln /p:Version=13.0.9999

      - name: Test
        run: dotnet test .\tests\**\bin\Debug\net472\MoBi*Tests.dll -v normal --no-build  --logger:"html;LogFileName=../testLog_Windows.html"

      - name: Push test log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: testLog_Windows
          path: ./testLog*.html