name: Build and Test

on:
  pull_request:
    branches:
    - develop

env:
  MAJOR: 12
  MINOR: 1
  RUN: ${{ github.run_number }}

jobs:

  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.300' 

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"
          dotnet restore

      - name: Build
        run: msbuild MoBi.sln /p:Version=12.1.9999

      - name: Test
        run: dotnet test .\tests\**\bin\Debug\net472\MoBi*Tests.dll -v normal --no-build  --logger:"html;LogFileName=../testLog_Windows.html"

      - name: Push test log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: testLog_Windows
          path: ./testLog*.html