name: Build and Test 12.3

on:
  pull_request:
    branches:
    - develop
  push:
    branches:
    - develop

permissions:
  contents: read
  packages: read

jobs:
  badge:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/test-csharp.yml@add_resuable_test_workflow
    with:
      temp-version: "12.3.9999"
  