name: Code Coverage

on:
    schedule:
      - cron: '0 1 * * 5'

jobs:
  cover:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Add NuGet repository
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"

      - name: Build
        run: dotnet build MoBi.sln /p:Version=13.0.999 -p:ExcludeDesigner=true

        
      - name: Cover and report
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/dotCover@main
        with:
          xml-configuration: dotcover.xml
          token: ${{ secrets.CODECOV_TOKEN }}