name: Code Coverage

on:
    schedule:
      - cron: '0 1 * * 5'

jobs:
  cover:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"
          nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
          nuget sources add -name utility -source https://ci.appveyor.com/nuget/ospsuite-utility 
          nuget sources add -name serializer -source https://ci.appveyor.com/nuget/ospsuite-serializer 
          nuget sources add -name databinding -source https://ci.appveyor.com/nuget/ospsuite-databinding 
          nuget sources add -name texreporting -source https://ci.appveyor.com/nuget/ospsuite-texreporting 
          nuget sources add -name databinding-devexpress -source https://ci.appveyor.com/nuget/ospsuite-databinding-devexpress 
          dotnet restore

      - name: Build
        run: msbuild MoBi.sln /p:Version=12.1.999

        
      - name: Cover and report
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/dotCover@main
        with:
          xml-configuration: dotcover.xml
          token: ${{ secrets.CODECOV_TOKEN }}